apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-sadeb
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: sadeb-be
              servicePort: 80
            path: /backend/?(.*)
            pathType: Prefix
          - backend:
              serviceName: sadeb-fe
              servicePort: 90
            path: /?(.*)
            pathType: Prefix

## run on azure shell
#helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
#helm install nginx-ingress ingress-nginx/ingress-nginx --set controller.replicaCount=1 --set controller.nodeSelector."beta\.kubernetes\.io/os"=linux --set defaultBackend.nodeSelector."beta\.kubernetes\.io/os"=linux --set controller.admissionWebhooks.patch.nodeSelector."beta\.kubernetes\.io/os"=linux