apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: image-pull-secret
data:
  .dockerconfigjson: {{ "{\"auths\": {\"retoibm.azurecr.io\": {\"username\": \"retoibm\", \"password\": \"Iv+FuMkv2yfGu4L+YHeF+G5HSiszDXwd\"}}}" | b64enc }}